### ISSUE TITLE
Support neovim 0.7 features

### ISSUE THREAD

**Issue by pta2002** [pta2002/nixvim#15]
Neovim 0.7 has just come out, and there are a few features which would be a great fit for nixvim:

- [x] support for autocomands - now with a lua API, so it's way easier to support
- [x] support lua keybinds (use `vim.keymap.set`)
- [x] support highlight groups
- [ ] support `filetype.lua

I plan to begin working on these in the following weeks - none of them should be particularly difficult

**Comment by pta2002** [comment]
Something extra which would probably be a good fit here - compatibility checks. Would be really helpful if we could short-circuit while still in Nix, and say "this feature requires neovim >= 0.7", or use a backwards-compatible way

**Comment by rummik** [comment]
Looks like we're already to [`v0.8.1`](https://github.com/neovim/neovim/releases/tag/v0.8.1), but that's not in NixOS unstable yet, let alone stable 😅

**Comment by GaetanLepage** [comment]
`v0.8.2` has been merged to `nixos-unstable` :)

**Comment by pta2002** [comment]
Yeah, I'll need to create a github project for all these features with individual issues, should be the better way to go about it honestly

**Comment by GaetanLepage** [comment]
@pta2002 what do you mean by "support `filetype.lua`" ?
From [this post](https://www.reddit.com/r/neovim/comments/rvwsl3/introducing_filetypelua_and_a_call_for_help/), it seems that the behavior can be changed by simply changing global variables.
Moreover, it seems that the lua filetype detection has been enabled by default since https://github.com/neovim/neovim/pull/19216.

I guess there is nothing to do for us here then. As this was the last thing on this list, we might close this issue.
Have I missed anything ?

**Comment by pta2002** [comment]
I think I meant support for generating filetype.lua files

**Comment by GaetanLepage** [comment]
> I think I meant support for generating filetype.lua files

Oh ok ! I have no idea how this works though...

**Comment by GaetanLepage** [comment]
I just remembered that @traxys already wrapped the `vim.fileype.add` function: https://github.com/pta2002/nixvim/pull/277
Do you think of any missing feature @pta2002 ?
