### ISSUE TITLE
Automatically infer extraPlugins used, if your config contains specific functions

### ISSUE THREAD

**Issue by Alexnortung** [pta2002/nixvim#221]
# Automatically infer extraPlugins, based on functions or commands used in config.

## Introduction

When writing a large configuration for neovim, it might be hard to keep track of where you are using specific commands from plugins.
Let's say I want to use `vim-bbye` which provides the `:Bdelete` command, you may have specified that you use the command from multiple places (maybe bufferline, keymaps, etc.). It may then be hard to remember all the places that you are trying to use this plugin's commands, thus it will be harder to know when to removed a plugin, when you are no longer using it.

## How could this change for the user?

The goal of this issue is to in some cases eliminate the need to put some plugins in the `extraPlugins` array, by automatically finding the dependencies (through some kind of command set).

For example if I wanted to use `vim-bbye`, I would not need to add it to `extraPlugins` if I am using it's commands from for example a bufferline plugin.

## Solution

I am really not sure how this could be solved or if it is even feasible. However I really like the idea from a user perspective.

### Idea 1

Being able to use some kind of imports in nix and use those instead of strings.

Before:

```nix
{
  plugins.bufferline =
    {
      closeCommand = "Bdelete %d";
    };
  extraPlugins = [ pkgs.vimPlugins.vim-bbye ];
}
```

after:

```nix
{
  plugins.bufferline =
    let
      Bdelete = import nixvim.commands.Bdelete;
    in
    {
      closeCommand = "${Bdelete} %d";
    };
}
```

However I don't really think this could work as imports don't have side effects and I don't think we can really trigger it in any way.

---

On the other side, we might be able to get around this if we restructure the way the config is built. I am thinking that the config would be built using strings and some other type for commands in a large array. 

Or instead of using a large array, it may insert some special characters that we can then look for and replace with the actual command and then add the plugin.

### Idea 2

I don't really like this idea and I believe it may not be feasible, but it might get something working without major restructuring.
After building the config, look through the entire config string for any occurence of a command and add the respective plugin.

---

I certainly believe this kind of functionality is possible and should be opt-in (which it is by design in idea 1).

I would really like some feedback for this issue, what do you think of the current ideas? Would there be a better way of doing it?

What do you think @pta2002 @GaetanLepage @traxys

**Comment by GaetanLepage** [comment]
Hello Alex,
To be perfectly honest, I am not really convinced by such a feature.
Here is why.
Obviously, wanting a better user experience should be our ultimate goal. However, in this case I am not sure it is a good thing.
The reason is the extra added complexity. The latter is dual:
- **For us (the developers):** Supporting this would lead to complicating the code base and the way our module works. As you pointed out, it would require some pretty advanced techniques which would make nixvim less "straightforward".
However, I am not at all intrinsically opposed to anything that is harder or more complex to implement. What matters at the end is the user. But still, we have to keep the code base as maintainable as possible.
- **For the user:** What I personally liked about nixvim when I found out about it, is that it is mostly straightforward:
  - It makes it possible to _translate_ your lua config to nix in a natural way. (Options are the same, they are just translated to lua very naturally).
  - It handles several things thanks to nix that the user can stop worrying about. (I think mostly about the plugin manager and the package dependencies like the language servers).
  But it does not do more than this. And, according to me, this is great. I get what you mean when you say "With this, the user can directly _use_ the plugin without explicitly requiring it". However, to me, you **should** be explicit about which plugin you want to install on your system. The behavior you want to push seems like the one a neovim distribution would have (such as LunarVim, NvChad...). In those, the chosen paradigm is different as they abstract many more things.
  From what I understand, nixvim is more a simple module that lets the power (and the responsibility) to the user.

This is my own opinion. Obviously, the final word should be Pedro's. I would be glad to hear what @traxys and @pta2002 think about this.

Anyway, thank you for bringing new ideas on the table :)

**Comment by Alexnortung** [comment]
Thanks for the feedback @GaetanLepage. I just thought this feature would fit nicely in nixvim since we are already utilizing the power of nix.

I totally agree with you that nixvim should be maintainable, and I don't think that the logic is too complex, we just need to change the way things are added and changed, I think.

On the other side, you may be right that this should be in a separate project. However it would be coolest to have the feature in nixvim in some way ;)

**Comment by pta2002** [comment]
IMO I mostly agree with what @GaetanLepage said. I think it'd very quickly turn into a maintenance nightmare. The only real way I can see this working would be something like what you initially suggested with the imports, but even then I think it'd very easily become a maintenance nightmare. I think a simpler way to do this would just be `plugins.[plugin].extraConfig = plugin: "${plugin}.setup(...)"` or something like that, basically a config parameter that lets you define your own config with the plugin's name in scope, acessible via the `plugin` parameter.

**Comment by GaetanLepage** [comment]
At first I had not really understood his proposal.
I think it is easier to stay in the NixOS/HM module paradigm (i.e. if I want to use `foo`, I **have** to set `foo.enable = true;`).

I cannot think about a lot of cases where this would be useful...

**Comment by Alexnortung** [comment]
Okay...

I mean we already infer some packages based on config, which is really good. I am pretty sure nvim-cmp sources are inferred from your config and I really think this is good user experience.

This proposal just sets out to allow commands from small plugins too.

I might try to come up with a solution. And if it doesn't fit in Nixvim I will probably make it some sort of plugin/module in a side project.

**Comment by GaetanLepage** [comment]
> I mean we already infer some packages based on config, which is really good. I am pretty sure nvim-cmp sources are inferred from your config and I really think this is good user experience.
> 
> This proposal just sets out to allow commands from small plugins too.

To me this is not the same thing. What we do now is enable a package or plugin which is a dependency (strict or optional) of the plugin you want to configure.
For instance, if I set `plugins.lualine.iconsEnabled` to `true`, nixvim will add the `nvim-web-devicons`.
In your example, you want to embed a command offered by another plugin in a separate one.

Actually your solution 1 (or a variation of it) seems legit in terms of technical solution.
The only thing is that I cannot get to imagine many examples of such _command imports_.

One last thing. I am willing to review and test any proposal code. I am really not closed to a solution proposition.
This is not a strong "no" at all. :)
At this stage, I just need to be more convinced of both the usefulness and the feasibility of it.

**Comment by Alexnortung** [comment]
I think I agree with your points on this one after a lot of thought. It may not be as easy as I had anticipated. I will close this issue, hopefully I might figure something out somehow.
