### ISSUE TITLE
Can't use `"lua"` (and other) plugin config types

### ISSUE THREAD

**Issue by ForsakenHarmony** [pta2002/nixvim#329]
**Plugin affected**: third party
**Nixpkgs channel**: 22.11
**Home-manager version**: 

## Description
home-manager allows you to choose which type of config you want to add
https://github.com/nix-community/home-manager/blob/master/modules/programs/neovim.nix#L16

## Config
```
{
  plugin = which-key-nvim;
  type = "lua";
  config = ''
    require("which-key").setup({})
  '';
}
```
throws
```
error: The option `home-manager.users.hrmny.programs.nixvim.extraPlugins."[definition 13-entry 17]".type' does not exist. Definition values:
       - In `/nix/store/8w1df8s8vxipfz20fxr6w3dzgk3y4d7q-source/flake.nix': "lua"
```

**Comment by traxys** [comment]
Nixvim does not work like home-manager, the extraPlugins are a list of derivations that are directly passed to neovim. You should not really need to use it directly, instead enabling plugins through 'plugins.<some-plugin>.enable'.

If your plugin is not packaged you will need to either open an issue to request for it, or add the plugin derivation to `extraPlugins` and the plugin configuration to `extraConfigLua`.

I think `which-key-nvim` is not packaged for nixvim so you would need the second approach

**Comment by ForsakenHarmony** [comment]
@traxys this is an example entry in `extraPlugins`

**Comment by traxys** [comment]
This is not really the goal of nixvim, the goal is mostly to have a convenient way to map the lua configuration as Nix expressions, and right now the only path we support is through global options in the nixvim module. We may want to explore other ways to package plugins in the future in order to support things like lazy loading, but nobody has looked into that yet.

In the meantime if you want I packaged `which-key-nvim` as a nixvim module, you can check the options [here](https://pta2002.github.io/nixvim/#_plugins_which_key_enable) (The documentation is not the best in the world, we need to improve it too)

Don't hesitate to give suggestions to improve nixvim!
