### ISSUE TITLE
`crates-nvim` is broken.

### ISSUE THREAD

**Issue by siph** [pta2002/nixvim#425]
**Plugin affected**: `crates-nvim`
**Nixpkgs channel**: `nixos-unstable`

## Description
Enabling `crates-nvim` as a module throws an error:
```nix
{
  plugins.crates-nvim.enable = true;
}
```
```shell
- ERROR Failed to run healthcheck for "crates" plugin. Exception:
  function health#check, line 25
  Vim(eval):E5108: Error executing lua ...myNeovimPackages/start/crates.nvim/lua/crates/health.lua:32: bad argument #1 to 'ipairs' (table expected, got nil)
  stack traceback:
  [C]: in function 'ipairs'
  ...myNeovimPackages/start/crates.nvim/lua/crates/health.lua:32: in function 'check'
  [string "luaeval()"]:1: in main chunk
```

The plugin does, however, work when added manually:
```nix
{
  extraPlugins = with pkgs.vimPlugins; [
    crates-nvim
  ];
  extraConfigLua = ''
    require('crates').setup({})
  '';
}
```

## Configuration
I tested this with a fresh config from the standalone template.

**Comment by GaetanLepage** [comment]
Thank you for reporting this issue.

First, you are not supposed to enable the `crates-nvim` plugin like you did.
Indeed, this plugin is automatically enabled when the `crates` source is added to `nvim-cmp.sources` list.
However, there is indeed a problem because for all of those `nvim-cmp` _source plugins_, we are not doing anything else than adding the package to `extraPlugins`. However, for this specific one, we should add the call to `require('crates').setup({})`.
@pta2002 @traxys, what approach would you like to take for this ? In the current implementation, there is no support to specify additional source plugin lua code as the plugin modules are automatically generated from a list of package names.
At least for `crates-nvim`, we should have somewhere:
```nix
config = mkIf config.plugins.nvim-cmp.enable {
  extraLuaConfig = ''
    require('crates').setup({})
  '';
};
```

**Comment by siph** [comment]
I see. [`crates.nvim`](https://github.com/Saecki/crates.nvim) is more than a completion source so this was unexpected behavior to me.

Although, I now realize I don't need to be explicitly enabling the `cmp` plugins if they're included in `nvim-cmp.sources` (with the exception of `luasnip`) so that helps clean up some of my config, thanks.
