### ISSUE TITLE
nvim-base16 not loaded before lualine

### ISSUE THREAD

**Issue by omernaveedxyz** [pta2002/nixvim#469]
**Plugin affected**: `nvim-base16` & `lualine`
**Nixpkgs channel**: nixpkgs-unstable
**Home-manager version**: Release 23.11

## Description
I get the following warning from Lualine when opening a file.
```theme(base16): nvim-base16 is not loaded yet, you should update your configuration to load it before lualine so that the colors from your colorscheme can be used, fallback to "tomorrow-night" theme.```

## Config
```nix
{ config, pkgs, ... }:

{
  programs.nixvim = {
    #
    enable = true;

    #
    colorschemes.base16 = {
      enable = true;
      colorscheme = "${config.colorScheme.slug}";
    };

    #
    plugins = {
      ... # (shortened for brevity)
      lualine.enable = true;
    };
  };
}
```

**Comment by GaetanLepage** [comment]
I was not able to reproduce with the following minimal config:
```nix
      {
        # inherit pkgs;
        module = {
          colorschemes.base16 = {
            enable = true;
            colorscheme = "circus";
          };
          plugins = {
            lualine.enable = true;
          };
        };
      };
```
What is the value of your `${config.colorScheme.slug}` ?

**Comment by omernaveedxyz** [comment]
> I was not able to reproduce with the following minimal config:
> 
> ```nix
> {
>   programs.nixvim = {
>     colorschemes.base16 = {
>       enable = true;
>       colorscheme = "circus";
>     };
>     plugins = {
>       lualine.enable = true;
>     };
>   };
> };
> ```
> 
> What is the value of your `${config.colorScheme.slug}` ?

That's strange. I'm able to replicate the issue just adding `enable = true` to that config.

```nix
programs.nixvim = {
  enable = true;
  colorschemes.base16 = {
    enable = true;
    colorscheme = "circus";
  };
  plugins = {
    lualine.enable = true;
  };
  extraPlugins = with pkgs.vimPlugins; [
    nvim-base16
  ];
};
```

**Comment by GaetanLepage** [comment]
Ok, I was indeed able to reproduce.
The message could be seen by calling `:LualineNotices`.

Intuitively, you could think that this error makes no sense because you added `nvim-base16` to your `extraPlugins`.
However, the error happens because both `base16-vim` and `nvim-base16` are installed simultaneously.

If you remove `nvim-base16` from `extraPlugins` and instead you set `colorschemes.base16.package = pkgs.vimPlugins.nvim-base16`, the error will be gone !

I have just proposed to switch to `nvim-base16` as a backend in #474. Hence, you would not have to do anything :)
